### ISSUE TITLE
emotions returns NaN values.

### ISSUE THREAD

**Issue by Mahadev77** [Affectiva/ios-sdk-samples#4]
Using swift 3.0 Detector detects faces but sometimes for some images "emotions" returns NaN values. why this is happening and how to solve it.

**Comment by ahamino** [comment]
Hey, the emotions might return NaNs if the head angle is outside the classifier confidence range.

**Comment by Mahadev77** [comment]
@ahamino  Thank You .
I will check it as you have explained.
